version: "3"
services:
  myportfolio:
    container_name: new_image
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
    ports:
      - "8000:5000"
    volumes:
      - .:/new_image
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql

volumes:
  mydatabase:
